import React, { type ReactNode } from "react";
import clsx from "clsx";
import { ThemeClassNames } from "@docusaurus/theme-common";
import useBaseUrl from "@docusaurus/useBaseUrl";
import type { Props } from "@theme/Footer/Layout";

import styles from "./styles.module.css";

/**
 * Zscaler-branded footer layout.
 *
 * Composes three vertical sections inside the standard `<footer>` shell:
 *
 *   1. **Link columns** — the existing 4-column links block driven by
 *      `themeConfig.footer.links` (Documentation / Community / More /
 *      Zscaler). Rendered by Docusaurus's stock `<FooterLinks/>` and
 *      passed in as the `links` prop.
 *
 *   2. **Corporate row** — mirrors zscaler.com's site-wide footer:
 *      wordmark + tagline on the left, social icons in the middle, the
 *      standard Sitemap / Privacy / Legal / Security / Cookie
 *      Preferences inline links on the right (vertically stacked on
 *      desktop, wrapping to one column on narrow viewports).
 *
 *   3. **Trademark copyright** — the long-form Zscaler™ trademark
 *      attribution, sourced from `themeConfig.footer.copyright`.
 *
 * Background color is black (corporate) rather than the previous navy
 * blue — see `--ifm-footer-background-color` in `src/css/custom.css`.
 */
export default function FooterLayout({
  style,
  links,
  copyright,
}: Props): ReactNode {
  return (
    <footer
      className={clsx(ThemeClassNames.layout.footer.container, "footer", {
        "footer--dark": style === "dark",
      })}
    >
      <div className="container container-fluid">
        {links}

        <CorporateRow />

        {copyright && (
          <div className={clsx(styles.copyrightWrapper, "text--center")}>{copyright}</div>
        )}
      </div>
    </footer>
  );
}

/**
 * The Zscaler corporate row — wordmark, tagline, social icons, and
 * site-wide policy links. Hard-coded here (rather than driven by
 * config) because every Zscaler property uses the same destinations
 * and the same tagline.
 */
function CorporateRow(): React.JSX.Element {
  const logoUrl = useBaseUrl("/img/zscaler.svg");
  const sitemapUrl = useBaseUrl("/sitemap");
  return (
    <div className={styles.corporate}>
      <div className={styles.corporateLeft}>
        <a
          href="https://www.zscaler.com/"
          aria-label="Zscaler"
          className={styles.corporateLogoLink}
        >
          <img
            src={logoUrl}
            alt="Zscaler"
            className={styles.corporateLogo}
            width={120}
            height={28}
          />
        </a>
        <p className={styles.corporateTagline}>
          Zscaler is universally recognized as the leader in zero trust.
          Leveraging the largest security cloud on the planet, Zscaler
          anticipates, secures, and simplifies the experience of doing business
          for the world&apos;s most established companies.
        </p>
      </div>

      <div className={styles.corporateSocial} aria-label="Zscaler on social media">
        <SocialLink href="https://www.facebook.com/Zscaler/" label="Facebook">
          <FacebookIcon />
        </SocialLink>
        <SocialLink
          href="https://www.linkedin.com/company/zscaler/"
          label="LinkedIn"
        >
          <LinkedInIcon />
        </SocialLink>
        <SocialLink href="https://twitter.com/zscaler" label="Twitter">
          <TwitterIcon />
        </SocialLink>
        <SocialLink
          href="https://www.youtube.com/user/ZscalerInc"
          label="YouTube"
        >
          <YouTubeIcon />
        </SocialLink>
      </div>

      <ul className={styles.corporateLinks}>
        <li>
          {/* Internal site sitemap (hand-curated, lives at
              src/pages/sitemap.tsx) — NOT zscaler.com/sitemap, which
              maps to the corporate website's IA and wouldn't help a
              docs reader find anything inside this site. The
              machine-readable feed consumed by search engines is at
              /sitemap.xml (auto-generated by the Docusaurus sitemap
              preset option). */}
          <a href={sitemapUrl}>Sitemap</a>
        </li>
        <li>
          <a href="https://www.zscaler.com/privacy-compliance/zscaler-privacy-policy">
            Privacy
          </a>
        </li>
        <li>
          <a href="https://www.zscaler.com/legal">Legal</a>
        </li>
        <li>
          <a href="https://trust.zscaler.com/">Security</a>
        </li>
        <li>
          {/* The href is a no-op anchor because the cookie consent modal
              is normally wired through a vendor script (OneTrust on
              zscaler.com). We expose the link for consistency, but
              clicking it just falls through to the page's privacy
              policy if no consent manager is loaded. */}
          <a href="https://www.zscaler.com/privacy-compliance/cookie-policy">
            Cookie Preferences
          </a>
        </li>
      </ul>
    </div>
  );
}

function SocialLink({
  href,
  label,
  children,
}: {
  href: string;
  label: string;
  children: ReactNode;
}): React.JSX.Element {
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      aria-label={label}
      className={styles.socialIcon}
    >
      {children}
    </a>
  );
}

/* Inline SVG icons keep the bundle small and avoid pulling in an icon
 * font. All icons share the 24x24 viewBox and `currentColor` fill so
 * they pick up the surrounding text color (light grey on the black
 * footer surface). */

function FacebookIcon(): React.JSX.Element {
  return (
    <svg viewBox="0 0 24 24" width="18" height="18" fill="currentColor" aria-hidden="true">
      <path d="M22 12c0-5.52-4.48-10-10-10S2 6.48 2 12c0 4.99 3.66 9.13 8.44 9.88v-6.99H7.9V12h2.54V9.8c0-2.5 1.49-3.89 3.77-3.89 1.09 0 2.23.2 2.23.2v2.46h-1.26c-1.24 0-1.63.77-1.63 1.56V12h2.77l-.44 2.89h-2.33v6.99C18.34 21.13 22 16.99 22 12z" />
    </svg>
  );
}

function LinkedInIcon(): React.JSX.Element {
  return (
    <svg viewBox="0 0 24 24" width="18" height="18" fill="currentColor" aria-hidden="true">
      <path d="M20.45 20.45h-3.55v-5.57c0-1.33-.02-3.03-1.85-3.03-1.85 0-2.14 1.45-2.14 2.94v5.66H9.36V9h3.41v1.56h.05c.48-.9 1.64-1.85 3.37-1.85 3.6 0 4.27 2.37 4.27 5.45v6.29zM5.34 7.43a2.06 2.06 0 1 1 0-4.12 2.06 2.06 0 0 1 0 4.12zM7.12 20.45H3.56V9h3.56v11.45zM22.23 0H1.77C.79 0 0 .77 0 1.72v20.56C0 23.23.79 24 1.77 24h20.46c.98 0 1.77-.77 1.77-1.72V1.72C24 .77 23.21 0 22.23 0z" />
    </svg>
  );
}

function TwitterIcon(): React.JSX.Element {
  return (
    <svg viewBox="0 0 24 24" width="18" height="18" fill="currentColor" aria-hidden="true">
      <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117L17.083 19.77z" />
    </svg>
  );
}

function YouTubeIcon(): React.JSX.Element {
  return (
    <svg viewBox="0 0 24 24" width="18" height="18" fill="currentColor" aria-hidden="true">
      <path d="M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z" />
    </svg>
  );
}
