import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Single unified sidebar for the Zscaler MCP Server documentation.
 *
 * Information architecture mirrors the CrowdStrike Falcon MCP docs-site
 * (https://crowdstrike.github.io/falcon-mcp) which lays everything out
 * as one top-down tree instead of splitting into per-navbar sub-sidebars.
 *
 * Section-to-section mapping with Falcon:
 *
 *   Falcon                      Zscaler
 *   --------------------------  ------------------------------------------
 *   Getting Started             Getting Started
 *   Usage                       Usage
 *   Modules (autogenerated)     Toolsets  — Falcon calls them "modules",
 *                               we call them "toolsets" (52 today across
 *                               9 services). The per-service pages live
 *                               here because each service IS effectively
 *                               a bundle of related toolsets.
 *   Deployment                  Deployment
 *   (n/a)                       Integrations — broken out separately
 *                               because we ship native plugins for 5
 *                               IDE/CLI clients (Claude, Cursor, etc.)
 *                               instead of treating them as examples.
 *   (n/a)                       Security — separate top-level section for
 *                               the MCP-client-auth / TLS / write-op
 *                               architecture docs.
 *   Development                 Development
 *   Examples                    (rolled into Integrations)
 *   Changelog                   Changelog
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    "intro",
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        "getting-started/installation",
        "getting-started/configuration",
        "getting-started/authentication",
        "getting-started/quickstart",
      ],
    },
    {
      type: "category",
      label: "Usage",
      collapsed: true,
      items: [
        "usage/cli",
        "usage/transports",
        "usage/editor-integration",
        "usage/service-configuration",
      ],
    },
    {
      type: "category",
      label: "Toolsets",
      collapsed: true,
      items: [
        "guides/toolsets",
        "guides/supported-tools",
        {
          type: "category",
          label: "Services",
          collapsed: true,
          items: [
            "services/overview",
            "services/zia",
            "services/zpa",
            "services/zdx",
            "services/zcc",
            "services/ztw",
            "services/zid",
            "services/easm",
            "services/zins",
            "services/zms",
          ],
        },
      ],
    },
    // Skills sit as a top-level sibling of Toolsets — they're the
    // "playbook" surface of the server: 42 guided multi-step
    // workflows that Claude / Cursor / Gemini auto-activate by
    // frontmatter description match. Source of truth is each
    // SKILL.md under skills/<service>/<name>/; the page itself is
    // rendered by docs-site/scripts/generate_skills_index.py.
    "guides/skills",
    {
      type: "category",
      label: "Deployment",
      collapsed: true,
      items: [
        // ----- AWS -----------------------------------------------------
        // AWS is a multi-shape deployment: the canonical container path
        // is Bedrock AgentCore. Strands lives next to it because it's
        // the agent runtime that consumes the AgentCore endpoint, and
        // Harness is the local-only test harness for AgentCore. All
        // three belong under AWS, not under "Integrations".
        {
          type: "category",
          label: "AWS",
          collapsed: false,
          items: [
            {
              type: "doc",
              id: "deployment/amazon-bedrock",
              label: "Bedrock AgentCore",
            },
            {
              type: "doc",
              id: "integrations/strands-agentcore",
              label: "Strands Agent client",
            },
            {
              type: "doc",
              id: "integrations/aws-harness",
              label: "AWS Harness (local test)",
            },
            {
              type: "doc",
              id: "deployment/secrets-manager",
              label: "Secrets Manager + Bedrock",
            },
          ],
        },
        // ----- Azure ---------------------------------------------------
        // The Azure README is one big multi-target guide. The sidebar
        // surfaces every target as a deep link into the right section of
        // the page (anchor-link sidebar entries) so admins can jump
        // directly to "Container Apps" without scrolling.
        {
          type: "category",
          label: "Azure",
          collapsed: false,
          items: [
            {
              type: "doc",
              id: "deployment/azure",
              label: "Overview",
            },
            {
              type: "link",
              label: "Container Apps",
              href: "/docs/deployment/azure#container-apps-deployment",
            },
            {
              type: "link",
              label: "Virtual Machine",
              href: "/docs/deployment/azure#vm-deployment",
            },
            {
              type: "link",
              label: "Kubernetes Service (AKS)",
              href: "/docs/deployment/azure#aks-deployment-preview",
            },
            {
              type: "doc",
              id: "deployment/azure-ai-foundry",
              label: "AI Foundry Agent",
            },
            {
              type: "doc",
              id: "deployment/entra-id-oidcproxy",
              label: "Entra ID OIDCProxy",
            },
          ],
        },
        // ----- Google Cloud --------------------------------------------
        {
          type: "category",
          label: "Google Cloud",
          collapsed: false,
          items: [
            {
              type: "doc",
              id: "deployment/gcp",
              label: "Overview",
            },
            {
              type: "link",
              label: "Cloud Run / GKE / Compute Engine",
              href: "/docs/deployment/gcp#option-1-standalone-mcp-server-gcpgcp_mcp_operationspy",
            },
            {
              type: "doc",
              id: "integrations/google-adk",
              label: "ADK Agent",
            },
          ],
        },
        // ----- Local ---------------------------------------------------
        // Container-only path that isn't cloud-platform-scoped. AWS
        // Secrets Manager moved out of here and into the AWS tree
        // above, since it's an AWS-specific integration.
        //
        // Order: the one-step setup script first (it's the
        // recommended entry point for new users), then the raw
        // Docker reference for advanced / scripted deployments.
        {
          type: "category",
          label: "Local",
          collapsed: false,
          items: [
            {
              type: "doc",
              id: "deployment/setup-script",
              label: "One-step setup script",
            },
            {
              type: "doc",
              id: "deployment/docker",
              label: "Docker",
            },
          ],
        },
      ],
    },
    // Integrations is now scoped tightly to the MCP-client and registry
    // surface — every cloud-platform deployment lives under "Deployment"
    // above, including Strands, Harness, and the ADK Agent.
    {
      type: "category",
      label: "Integrations",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "MCP Clients",
          collapsed: false,
          items: [
            "integrations/claude",
            "integrations/cursor",
            "integrations/gemini-cli",
            "integrations/kiro",
            "integrations/vscode",
          ],
        },
        {
          type: "category",
          label: "Registries",
          collapsed: false,
          // Same anchor-link pattern as Azure deployment targets:
          // each registry is its own sidebar entry that deep-links
          // straight to the matching section on the registries
          // overview page. There is exactly one entry per registry —
          // the GitHub MCP Registry deep-dive page
          // (integrations/github-registry, auto-mirrored from
          // integrations/github/README.md) is still reachable via
          // the inline "see the GitHub MCP Registry page" link in
          // the overview section, so we don't surface it as a
          // separate sidebar entry to avoid duplication.
          items: [
            {
              type: "doc",
              id: "integrations/registries",
              label: "Overview",
            },
            {
              type: "link",
              label: "Cursor Marketplace",
              href: "/docs/integrations/registries#cursor-marketplace",
            },
            {
              type: "link",
              label: "Claude Marketplace",
              href: "/docs/integrations/registries#claude-marketplace",
            },
            {
              type: "link",
              label: "Official MCP Registry",
              href: "/docs/integrations/registries#official-mcp-registry",
            },
            {
              type: "link",
              label: "Docker MCP Hub",
              href: "/docs/integrations/registries#docker-mcp-hub",
            },
            {
              type: "link",
              label: "GitHub MCP Registry",
              href: "/docs/integrations/registries#github-mcp-registry",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Security",
      collapsed: true,
      items: [
        "security/write-operations",
        "security/mcp-client-auth",
        "security/tls-and-hardening",
      ],
    },
    {
      type: "category",
      label: "Development",
      collapsed: true,
      items: [
        "development/contributing",
        "development/building-from-source",
      ],
    },
    {
      type: "category",
      label: "Help & Support",
      collapsed: true,
      items: ["guides/troubleshooting", "guides/support"],
    },
    "changelog",
  ],
};

export default sidebars;
