import React from "react";
import Layout from "@theme/Layout";
import Link from "@docusaurus/Link";

import styles from "./sitemap.module.css";

/**
 * Hand-curated sitemap of the documentation site.
 *
 * This is the destination of the **Sitemap** link in the corporate
 * footer row (rendered by `src/theme/Footer/Layout/index.tsx`). It is
 * intentionally a single hand-maintained page rather than an
 * auto-generated tree because:
 *
 *   - We want the same 4-column layout the OneAPI Automation Hub uses,
 *     not an exhaustive recursive walk of every docs URL.
 *   - The section headings and ordering encode a small editorial
 *     judgement about what readers go looking for first ("I want to
 *     find a Service", "I want to find a Deployment guide", etc.)
 *     which a generated index can't express.
 *
 * The XML sitemap consumed by search engines is a separate concern —
 * that one *is* auto-generated by the `sitemap` preset option in
 * `docusaurus.config.ts` and served at `/sitemap.xml`.
 */

type SitemapLink = {
  label: string;
  to: string;
};

type SitemapColumn = {
  title: string;
  links: SitemapLink[];
};

const COLUMNS: SitemapColumn[] = [
  {
    title: "Documentation",
    links: [
      { label: "Introduction", to: "/docs/intro" },
      { label: "Installation", to: "/docs/getting-started/installation" },
      { label: "Configuration", to: "/docs/getting-started/configuration" },
      { label: "Authentication", to: "/docs/getting-started/authentication" },
      { label: "Quickstart", to: "/docs/getting-started/quickstart" },
      { label: "CLI", to: "/docs/usage/cli" },
      { label: "Transports", to: "/docs/usage/transports" },
      { label: "Editor Integration", to: "/docs/usage/editor-integration" },
      {
        label: "Service Configuration",
        to: "/docs/usage/service-configuration",
      },
    ],
  },
  {
    title: "Services & Toolsets",
    links: [
      { label: "Toolsets", to: "/docs/guides/toolsets" },
      { label: "Supported Tools", to: "/docs/guides/supported-tools" },
      { label: "Skills", to: "/docs/guides/skills" },
      { label: "ZIA — Internet Access", to: "/docs/services/zia" },
      { label: "ZPA — Private Access", to: "/docs/services/zpa" },
      { label: "ZDX — Digital Experience", to: "/docs/services/zdx" },
      { label: "ZCC — Client Connector", to: "/docs/services/zcc" },
      { label: "ZTW — Workload Segmentation", to: "/docs/services/ztw" },
      { label: "ZIdentity", to: "/docs/services/zid" },
      { label: "EASM", to: "/docs/services/easm" },
      { label: "Z-Insights", to: "/docs/services/zins" },
      { label: "ZMS — Microsegmentation", to: "/docs/services/zms" },
    ],
  },
  {
    title: "Deployment",
    links: [
      { label: "Bedrock AgentCore (AWS)", to: "/docs/deployment/amazon-bedrock" },
      {
        label: "Strands Agent client",
        to: "/docs/integrations/strands-agentcore",
      },
      {
        label: "AWS Harness (local test)",
        to: "/docs/integrations/aws-harness",
      },
      {
        label: "Secrets Manager + Bedrock",
        to: "/docs/deployment/secrets-manager",
      },
      { label: "Azure Container Apps / VM / AKS", to: "/docs/deployment/azure" },
      {
        label: "Azure AI Foundry Agent",
        to: "/docs/deployment/azure-ai-foundry",
      },
      {
        label: "Entra ID OIDCProxy",
        to: "/docs/deployment/entra-id-oidcproxy",
      },
      { label: "Google Cloud", to: "/docs/deployment/gcp" },
      { label: "Google ADK Agent", to: "/docs/integrations/google-adk" },
      { label: "Setup Script", to: "/docs/deployment/setup-script" },
      { label: "Docker", to: "/docs/deployment/docker" },
    ],
  },
  {
    title: "Integrations & More",
    links: [
      { label: "Claude", to: "/docs/integrations/claude" },
      { label: "Cursor", to: "/docs/integrations/cursor" },
      { label: "Gemini CLI", to: "/docs/integrations/gemini-cli" },
      { label: "Kiro IDE", to: "/docs/integrations/kiro" },
      { label: "VS Code", to: "/docs/integrations/vscode" },
      { label: "Registries", to: "/docs/integrations/registries" },
      { label: "Write Operations", to: "/docs/security/write-operations" },
      { label: "MCP Client Auth", to: "/docs/security/mcp-client-auth" },
      { label: "TLS & Hardening", to: "/docs/security/tls-and-hardening" },
      { label: "Contributing", to: "/docs/development/contributing" },
      { label: "Troubleshooting", to: "/docs/guides/troubleshooting" },
      { label: "Changelog", to: "/docs/changelog" },
    ],
  },
];

export default function SitemapPage(): React.JSX.Element {
  return (
    <Layout
      title="Sitemap"
      description="A hand-curated map of every section of the Zscaler MCP Server documentation."
    >
      <main className={styles.sitemapContainer}>
        <div className={styles.sitemapInner}>
          <h1 className={styles.title}>Sitemap</h1>

          <div className={styles.columns}>
            {COLUMNS.map((column) => (
              <section key={column.title} className={styles.column}>
                <h2 className={styles.columnTitle}>{column.title}</h2>
                <ul className={styles.columnLinks}>
                  {column.links.map((link) => (
                    <li key={link.to}>
                      <Link to={link.to}>{link.label}</Link>
                    </li>
                  ))}
                </ul>
              </section>
            ))}
          </div>
        </div>
      </main>
    </Layout>
  );
}
