name: Python Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.11"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@39eb6c9dde236bbc368681611e63120a6eb4afac
        with:
          version: "latest"
          activate-environment: true

      - name: Install dependencies
        run: |
          uv sync --extra dev

      - name: Lint imports
        run: |
          ruff check . --select I

      - name: Lint with Ruff
        run: |
          ruff check .